"use client";
import { usePathname } from "next/navigation";
import { JsonLd } from "./JsonLd";
const SITE_URL = "https://apexbatch.com";
const DESCRIPTION = "ApexBatch provides precision manufacturing services for custom metal and plastic parts, supporting prototype validation, pilot production, batch manufacturing, and repeat production";
const IMAGES: Record<string, string> = { "/": "https://apex-batch-images.s3.us-east-1.amazonaws.com/home/1-homepage-banner.webp", "/cnc-machining": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/cnc-machining/1-custom-cnc-machining-services-banner.webp", "/cnc-milling": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/cnc-machining/1-custom-cnc-machining-services-banner.webp", "/cnc-turning": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/cnc-machining/1-custom-cnc-machining-services-banner.webp", "/die-casting": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/cnc-machining/1-custom-cnc-machining-services-banner.webp", "/injection-molding": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/injection-molding/1-plastic-injection-molding-manufacturer-banner.webp", "/insert-molding": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/injection-molding/1-plastic-injection-molding-manufacturer-banner.webp", "/molding-services": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/injection-molding/1-plastic-injection-molding-manufacturer-banner.webp", "/overmolding": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/injection-molding/1-plastic-injection-molding-manufacturer-banner.webp", "/sheet-metal-fabrication": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/injection-molding/1-plastic-injection-molding-manufacturer-banner.webp", "/extrusion-services": "https://apex-batch-images.s3.us-east-1.amazonaws.com/services/injection-molding/1-plastic-injection-molding-manufacturer-banner.webp" };
const LABELS: Record<string, string> = { "/": "Home", "/blog": "Blog", "/about": "About ApexBatch", "/contact": "Contact Us", "/quality": "Quality Assurance", "/reviews": "Customer Reviews", "/privacy-policy": "Privacy Policy", "/terms-and-conditions": "Terms and Conditions" };
function label(path: string) { return LABELS[path] || path.split("/").filter(Boolean).map((part) => part.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())).join(" "); }
export function RouteStructuredData() { const pathname = usePathname(); if (!pathname || pathname.startsWith("/admin") || pathname.startsWith("/api") || pathname === "/q4-announcement-preview") return null; const url = `${SITE_URL}${pathname === "/" ? "" : pathname}`; const image = IMAGES[pathname]; const graph: Record<string, unknown>[] = [{ "@context": "https://schema.org", "@type": "WebPage", "@id": `${url}#webpage`, url, name: label(pathname), description: DESCRIPTION, isPartOf: { "@id": `${SITE_URL}/#website` }, about: { "@id": `${SITE_URL}/#organization` }, ...(image ? { primaryImageOfPage: { "@id": `${url}#primaryimage` } } : {}) }]; if (image) graph.push({ "@context": "https://schema.org", "@type": "ImageObject", "@id": `${url}#primaryimage`, url: image, contentUrl: image, caption: label(pathname) }); const parts = pathname.split("/").filter(Boolean); if (parts.length > 1 || (parts.length === 1 && !["about", "contact", "privacy-policy", "terms-and-conditions"].includes(parts[0]))) graph.push({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE_URL }, ...parts.map((part, index) => { const partPath = `/${parts.slice(0, index + 1).join("/")}`; return { "@type": "ListItem", position: index + 2, name: label(partPath), item: `${SITE_URL}${partPath}` }; })] }); return <JsonLd data={graph} />; }
